images:
  - name: registry.home.arpa/pigeon-api
    newTag: "0.6"
  - name: registry.home.arpa/pigeon-ui
    newTag: "0.6"
namespace: pigeon
resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - cert.yaml
  - ingress-route.yaml