images:
  - name: registry.kabanos.xyz/pigeon-api
    newTag: "0.11"
  - name: registry.kabanos.xyz/pigeon-ui
    newTag: "0.6"
namespace: pigeon
resources:
  - namespace.yaml
  - api-deployment.yaml
  - api-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - cert.yaml
  - ingress-route.yaml